permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
encoding: utf-8

kramdown:
  input: GFM

# 作者信息
author:
  name: 张伟
  email: georginzhang@163.com
  link: 
  weibo: 
  github: http://github.com/georginzhang

# 站点信息
title:张伟的博客
description: 个人博客(georginzhang);整理、记载关于工具/资源/生活/技术/读书/影音等经验和思考;
url: http://georginzhang.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://oci3gtafy.bkt.clouddn.com/image/icon.jpg
favicon: http://oci3gtafy.bkt.clouddn.com/image/icon.ico

# google analytics 设置
ga:
  id: UA-86109050-1
  url: georginzhang.github.io

# disqus 设置
disqus:
  shortname: georginzhang

#rake configuration on 2016-03-01
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/georginzhang.github.com/
